import _includes from 'lodash.includes'
import * as FILTERS from '@/constants/interval-filters.js'

export const FILTER_QUERY_MONTH_1 = 'january'
export const FILTER_QUERY_MONTH_2 = 'february'
export const FILTER_QUERY_MONTH_3 = 'march'
export const FILTER_QUERY_MONTH_4 = 'april'
export const FILTER_QUERY_MONTH_5 = 'may'
export const FILTER_QUERY_MONTH_6 = 'june'
export const FILTER_QUERY_MONTH_7 = 'july'
export const FILTER_QUERY_MONTH_8 = 'august'
export const FILTER_QUERY_MONTH_9 = 'september'
export const FILTER_QUERY_MONTH_10 = 'october'
export const FILTER_QUERY_MONTH_11 = 'november'
export const FILTER_QUERY_MONTH_12 = 'december'

export const FILTER_QUERY_SEASON_SUMMER = 'summer'
export const FILTER_QUERY_SEASON_AUTUMN = 'autumn'
export const FILTER_QUERY_SEASON_WINTER = 'winter'
export const FILTER_QUERY_SEASON_SPRING = 'spring'

export const FILTER_QUERY_QUARTER_Q1 = 'q1'
export const FILTER_QUERY_QUARTER_Q2 = 'q2'
export const FILTER_QUERY_QUARTER_Q3 = 'q3'
export const FILTER_QUERY_QUARTER_Q4 = 'q4'

export const FILTER_QUERY_HALFYEAR_1ST = '1st-half'
export const FILTER_QUERY_HALFYEAR_2ND = '2nd-half'

export const FILTER_QUERY_NONE = 'all'

export const FILTER_QUERIES = {}
FILTER_QUERIES[FILTER_QUERY_MONTH_1] = FILTERS.FILTER_MONTH_1
FILTER_QUERIES[FILTER_QUERY_MONTH_2] = FILTERS.FILTER_MONTH_2
FILTER_QUERIES[FILTER_QUERY_MONTH_3] = FILTERS.FILTER_MONTH_3
FILTER_QUERIES[FILTER_QUERY_MONTH_4] = FILTERS.FILTER_MONTH_4
FILTER_QUERIES[FILTER_QUERY_MONTH_5] = FILTERS.FILTER_MONTH_5
FILTER_QUERIES[FILTER_QUERY_MONTH_6] = FILTERS.FILTER_MONTH_6
FILTER_QUERIES[FILTER_QUERY_MONTH_7] = FILTERS.FILTER_MONTH_7
FILTER_QUERIES[FILTER_QUERY_MONTH_8] = FILTERS.FILTER_MONTH_8
FILTER_QUERIES[FILTER_QUERY_MONTH_9] = FILTERS.FILTER_MONTH_9
FILTER_QUERIES[FILTER_QUERY_MONTH_10] = FILTERS.FILTER_MONTH_10
FILTER_QUERIES[FILTER_QUERY_MONTH_11] = FILTERS.FILTER_MONTH_11
FILTER_QUERIES[FILTER_QUERY_MONTH_12] = FILTERS.FILTER_MONTH_12

FILTER_QUERIES[FILTER_QUERY_SEASON_SUMMER] = FILTERS.FILTER_SEASON_SUMMER
FILTER_QUERIES[FILTER_QUERY_SEASON_AUTUMN] = FILTERS.FILTER_SEASON_AUTUMN
FILTER_QUERIES[FILTER_QUERY_SEASON_WINTER] = FILTERS.FILTER_SEASON_WINTER
FILTER_QUERIES[FILTER_QUERY_SEASON_SPRING] = FILTERS.FILTER_SEASON_SPRING

FILTER_QUERIES[FILTER_QUERY_QUARTER_Q1] = FILTERS.FILTER_QUARTER_Q1
FILTER_QUERIES[FILTER_QUERY_QUARTER_Q2] = FILTERS.FILTER_QUARTER_Q2
FILTER_QUERIES[FILTER_QUERY_QUARTER_Q3] = FILTERS.FILTER_QUARTER_Q3
FILTER_QUERIES[FILTER_QUERY_QUARTER_Q4] = FILTERS.FILTER_QUARTER_Q4

FILTER_QUERIES[FILTER_QUERY_HALFYEAR_1ST] = FILTERS.FILTER_HALFYEAR_1ST
FILTER_QUERIES[FILTER_QUERY_HALFYEAR_2ND] = FILTERS.FILTER_HALFYEAR_2ND

FILTER_QUERIES[FILTER_QUERY_NONE] = FILTERS.FILTER_NONE

const filterQueries = Object.keys(FILTER_QUERIES)

export function isValidFilterQuery(filter) {
  return _includes(filterQueries, filter)
}

export function getFilterQueryByFilter(filter) {
  const find = filterQueries.find((d) => FILTER_QUERIES[d] === filter)
  return find && find !== FILTER_QUERY_NONE ? find : null
}

export function getFilterByFilterQuery(query) {
  return FILTER_QUERIES[query] || null
}
