export const DOMAINS = 'DOMAINS';
export const FETCHING = 'FETCHING';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_ERROR_MESSAGE = 'FETCH_ERROR_MESSAGE';
export const CHART_ZOOMED = 'CHART_ZOOMED';
export const VIS_TYPE = 'VIS_TYPE';
export const MIN_PERIOD = 'MIN_PERIOD';
export const GROUP_TO_PERIODS = 'GROUP_TO_PERIODS';

export const EXPORT_DATA = 'EXPORT_DATA';
export const EXPORT_REGION = 'EXPORT_REGION';
export const EXPORT_PNG = 'EXPORT_PNG';

export const RANGE_SUMMARY = 'RANGE_SUMMARY';
export const POINT_SUMMARY = 'POINT_SUMMARY';
export const POINT_HOVERED = 'POINT_HOVERED';

export const SELECTED_DATES = 'SELECTED_DATES';
export const DATA_END_DATE = 'DATA_END_DATE';
export const RANGE = 'RANGE';

export const TEMPERATURE_PANEL = 'TEMPERATURE_PANEL';
export const PRICE_PANEL = 'PRICE_PANEL';
export const SUMMARY_PANEL = 'SUMMARY_PANEL';

export const FEATURE_TOGGLE_EXTERNAL_DATA = 'FEATURE_TOGGLE_EXTERNAL_DATA';
export const FEATURE_TOGGLE_MORE_DATE_RANGES = 'FEATURE_TOGGLE_MORE_DATE_RANGES';
export const FEATURE_TOGGLE_RECORDS_TABLE = 'FEATURE_TOGGLE_RECORDS_TABLE';
