export const UPDATE_EXPORT_DATA = 'UPDATE_EXPORT_DATA';
export const UPDATE_EXPORT_REGION = 'UPDATE_EXPORT_REGION';
export const UPDATE_EXPORT_PNG = 'UPDATE_EXPORT_PNG';

export const RANGE_SUMMARY = 'RANGE_SUMMARY';
export const POINT_SUMMARY = 'POINT_SUMMARY';
export const POINT_HOVERED = 'POINT_HOVERED';
