export const REGION = 'REGION';
export const DOMAINS = 'DOMAINS';
export const DOMAIN_GROUPS = 'DOMAIN_GROUPS';
export const USE_GROUPS = 'USE_GROUPS';

export const FETCHING = 'FETCHING';
export const ERROR = 'ERROR';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const WARNING = 'WARNING';
export const WARNING_MESSAGE = 'WARNING_MESSAGE';

export const VIS_TYPE = 'VIS_TYPE';

export const CHART_ZOOMED = 'CHART_ZOOMED';
export const CHART_TYPE_TRANSITION = 'CHART_TYPE_TRANSITION';
export const CHART_PERIOD = 'CHART_PERIOD';
export const CHART_MIN_PERIOD = 'CHART_MIN_PERIOD';
export const CHART_GROUP_TO_PERIODS = 'CHART_GROUP_TO_PERIODS';
export const CHART_CURRENT_HOVER_SERIES = 'CHART_CURRENT_HOVER_SERIES';
export const CHART_CLIENT_X = 'CHART_CLIENT_X';
export const CHART_CLIENT_Y = 'CHART_CLIENT_Y';
export const CHART_WIDTH = 'CHART_WIDTH';
export const CHART_HEIGHT = 'CHART_HEIGHT';
export const CHART_MAIN_PANEL_HOVER = 'CHART_MAIN_PANEL_HOVER';

export const NEM_URLS = 'NEM_URLS';
export const NEM_DATA = 'NEM_DATA';
export const GROUPED_NEM_DATA = 'GROUPED_NEM_DATA';
export const NEM_DATA_TRIM = 'NEM_DATA_TRIM';
export const NEM_TRIM = 'NEM_TRIM';
export const NEM_RESPONSE_DATA = 'NEM_RESPONSE_DATA';
export const NEM_TERA = 'NEM_TERA';

export const EXPORT_DATA = 'EXPORT_DATA';
export const EXPORT_REGION = 'EXPORT_REGION';
export const EXPORT_PNG = 'EXPORT_PNG';
export const EXPORT_ATTRIBUTION = 'EXPORT_ATTRIBUTION';
export const EXPORT_SHOW_PERCENT = 'EXPORT_SHOW_PERCENT';

export const RANGE_SUMMARY = 'RANGE_SUMMARY';
export const POINT_SUMMARY = 'POINT_SUMMARY';
export const GROUP_POINT_SUMMARY = 'GROUP_POINT_SUMMARY';
export const POINT_HOVERED = 'POINT_HOVERED';
export const CONTRIBUTION_TYPE = 'CONTRIBUTION_TYPE';
export const SUMMARY_DISABLED_SERIES = 'SUMMARY_DISABLED_SERIES';
export const SUMMARY_AVAILABLE_FTS = 'SUMMARY_AVAILABLE_FTS';

export const SELECTED_DATES = 'SELECTED_DATES';
export const DATA_END_DATE = 'DATA_END_DATE';
export const RANGE = 'RANGE';
export const YEARS = 'YEARS';
export const WEEKS = 'WEEKS';
export const INTERVAL = 'INTERVAL';
export const DATE_PERIOD_TRANSITION = 'DATE_PERIOD_TRANSITION';

export const TEMPERATURE_PANEL = 'TEMPERATURE_PANEL';
export const PRICE_PANEL = 'PRICE_PANEL';
export const SUMMARY_PANEL = 'SUMMARY_PANEL';
export const EMISSION_VOLUME_PANEL = 'EMISSION_VOLUME_PANEL';
export const EMISSION_INTENSITY_PANEL = 'EMISSION_INTENSITY_PANEL';
export const PANELS_SELECTIONS = 'PANELS_SELECTIONS';
export const PANELS_SELECTED = 'PANELS_SELECTED';

export const FACILITY_DATA = 'FACILITY_DATA';
export const FACILITY_RESPONSE_DATA = 'FACILITY_RESPONSE_DATA';
export const FACILITY_EXPORT_DATA = 'FACILITY_EXPORT_DATA';
export const FACILITY_SELECTED_TECHS = 'FACILITY_SELECTED_TECHS';
export const FACILITY_VIEW = 'FACILITY_VIEW';

export const GROUP_SELECTIONS = 'GROUP_SELECTIONS';
export const GROUP_SELECTED = 'GROUP_SELECTED';

export const FEATURE_TOGGLE_LOCAL_DATA = 'FEATURE_TOGGLE_LOCAL_DATA';
export const FEATURE_TOGGLE_MORE_DATE_RANGES = 'FEATURE_TOGGLE_MORE_DATE_RANGES';
export const FEATURE_TOGGLE_EMISSIONS = 'FEATURE_TOGGLE_EMISSIONS';

