export const DOMAINS = 'DOMAINS';
export const FETCHING = 'FETCHING';
export const ERROR = 'ERROR';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const VIS_TYPE = 'VIS_TYPE';

export const CHART_ZOOMED = 'CHART_ZOOMED';
export const CHART_TYPE_TRANSITION = 'CHART_TYPE_TRANSITION';
export const CHART_PERIOD = 'CHART_PERIOD';
export const CHART_MIN_PERIOD = 'CHART_MIN_PERIOD';
export const CHART_GROUP_TO_PERIODS = 'CHART_GROUP_TO_PERIODS';

export const NEM_DATA = 'NEM_DATA';
export const NEM_RESPONSE_DATA = 'NEM_RESPONSE_DATA';

export const EXPORT_DATA = 'EXPORT_DATA';
export const EXPORT_REGION = 'EXPORT_REGION';
export const EXPORT_PNG = 'EXPORT_PNG';
export const EXPORT_ATTRIBUTION = 'EXPORT_ATTRIBUTION';

export const RANGE_SUMMARY = 'RANGE_SUMMARY';
export const POINT_SUMMARY = 'POINT_SUMMARY';
export const POINT_HOVERED = 'POINT_HOVERED';
export const CONTRIBUTION_TYPE = 'CONTRIBUTION_TYPE';
export const SUMMARY_DISABLED_SERIES = 'SUMMARY_DISABLED_SERIES';

export const SELECTED_DATES = 'SELECTED_DATES';
export const DATA_END_DATE = 'DATA_END_DATE';
export const RANGE = 'RANGE';
export const YEARS = 'YEARS';
export const WEEKS = 'WEEKS';
export const INTERVAL = 'INTERVAL';

export const TEMPERATURE_PANEL = 'TEMPERATURE_PANEL';
export const PRICE_PANEL = 'PRICE_PANEL';
export const SUMMARY_PANEL = 'SUMMARY_PANEL';

export const FEATURE_TOGGLE_LOCAL_DATA = 'FEATURE_TOGGLE_LOCAL_DATA';
export const FEATURE_TOGGLE_MORE_DATE_RANGES = 'FEATURE_TOGGLE_MORE_DATE_RANGES';
