<template>
  <div class="ft-region-chart-wrapper">

    <h3>Source of Generation from xxxx — xxxx</h3>
    <h4>Share of electricity generated by <a href="#">Black Coal</a></h4>
    <div class="loader" v-if="!chartRendered"></div>
    <div id="ft-region-vis"></div>
  </div>
</template>

<script>
import * as moment from 'moment';
import { mapGetters } from 'vuex';

import { FUEL_TECH, REGIONS } from '../utils/FuelTechConfig'

const focusFt = 'black_coal'

export default {
  created() {
    this.$store.dispatch('fetchFtGen');
  },
  data() {
    return {
      chart: null,
      chartRendered: false
    }
  },
  computed: {
    ...mapGetters({
      ftGen: 'getFtGen'
    })
  },
  methods: {
    focusFt(key) {
      const newArray = this.ftGen.concat([])
      updateFTValue(key, newArray)

      this.chart.dataProvider = newArray
      this.chart.validateData()
    }
  },
  watch: {
    ftGen(newData) {
      const newArray = newData.concat([])

      this.chart = AmCharts.makeChart('ft-region-vis', {
        type: 'serial',
        categoryField: 'regionId',
        rotate: true,
        dataProvider: [],
        categoryAxis: {
          position: 'top',
          labelRotation: 0,
          labelFunction(valueText, serialDataItem, categoryAxis) {
            if (valueText === '') {
              return valueText
            } else {
              const found = REGIONS.find(region => region.id === valueText)
              return found.label
            }
          }
        },
        valueAxes: [{
          dashLength: 6,
          zeroGridAlpha: 0,
          stackType: 'regular',
          minimum: -100,
          maximum: 100,
          labelFunction(item) {
            return Math.abs(item)
          },
        }],
        graphs: generateGraphsArr()
        
      })

      updateFTValue(focusFt, newArray)
      this.chart.dataProvider = newArray
      this.chart.validateData()
      this.chartRendered = true
    }
  }
}

function updateFTValue(ft, data) {
  data.forEach(d => {
    Object.keys(d).forEach(k => {
      if (k !== ft && k !== 'regionId') {
        d[k] = -d[k]
      }
    })
  })
  
  data.sort((a, b) => {
    return b[ft] - a[ft]
  })
}

function generateGraphsArr() {
  const graphArr = []

  Object.keys(FUEL_TECH).forEach(key => {
    if (key !== 'NETINTERCHANGE') {
      // ignore NETINTERCHANGE
      graphArr.push({
        valueField: key,
        type: 'column',
        fillAlphas: .9,
        lineAlpha: 0,
        lineColor: FUEL_TECH[key].colour,
        useDataSetColors: false,
        
      })
    } 
  })

  return graphArr
}
</script>

<style scoped>
a {
  color: steelblue;
  text-decoration: none;
  border-bottom: 1px dotted steelblue;
  font-size: 1.1rem;
}
h4 {
  text-align: center;
  margin: 0;
}
#ft-region-vis {
  width: 100%;
  height: 300px;
}

</style>
