name: dev build to s3
on:
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
      NUXT_ENV_HEADER_X_ONUU: ${{ secrets.NUXT_ENV_HEADER_X_ONUU }}
    steps:
      - uses: actions/checkout@main
      - uses: awact/cloudfront-action@master
        env:
          AWS_REGION: 'ap-southeast-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn generate-dev
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist'
          destination_dir: ''
